### ISSUE TITLE
GMP: Cross-net message receipts

### ISSUE THREAD

**Issue by adlrocha** [consensus-shipyard/ipc#531]
Implementation of the logic that triggers the message receipt (ACK) as detailed [here](https://www.notion.so/pl-strflt/General-Message-Passing-7686edb5b65c4f9086fa4d4288c35906?pvs=4#eaa5a2f1a5a142e6ad7231abd5164484)

**Comment by raulk** [comment]
There was an open point re: delivery guarantees of receipts back to the origin. Because both the delivery of the request and the receipt are at the discretion of relayers/validators, the IPC framework cannot make any delivery guarantees now. We need to discuss timeouts and when is a good time for the origin contract to consider a response "terminally undelivered" and trigger a rollback if needed.

**Comment by raulk** [comment]
Merged to `main` in https://github.com/consensus-shipyard/ipc/pull/543.

**Comment by raulk** [comment]
And my comment above was solved by returning a Result with Transfers 🎉
