### ISSUE TITLE
Contract deployment bug

### ISSUE THREAD

**Issue by snissn** [consensus-shipyard/ipc#597]
From working on the uniswap tests, this seems to fail:

```
 curl -X POST -H "Content-Type: application/json"    --data '{"jsonrpc":"2.0","method":"eth_sendTransaction","params":[{"from":"0x2bfadcdd599e49b61e939baec651c3f5d4b421ab","gas":"0x3376a","maxFeePerGas":"0xa","maxPriorityFeePerGas":"0x0","data":"0x608060405234801561001057600080fd5b506102db806100206000396000f3fe608060405234801561001057600080fd5b506004361061004b5760003560e01c806246b777146100505780636b83cf261461007f578063d230d2"}], "id":42}'   http://localhost:8545
```
```
{"jsonrpc":"2.0","error":{"code":-32601,"message":"Method not found"},"id":42}%
```

to replicate first fund the account 0x2bfadcdd599e49b61e939baec651c3f5d4b421ab with some eth.

This contract deployment transaction is coming from hardhat and ethers during the uniswap test to deploy a small test contract BitMathTest.sol contract

**Comment by raulk** [comment]
`eth_sendTransaction` sends an unsigned transaction to the client for both signing and submission. Neither Fendermint nor Lotus support `eth_sendTransaction` because neither implementation acts as an Eth wallet. Both implementations support only `eth_sendRawTransaction`, which sends a signed transaction merely for checking and submission. We don't expect to support `eth_sendTransaction` ever, so perhaps we should disable the test if it absolutely requires this?

**Comment by snissn** [comment]
Thank you for explaining this to me @raulk . I agree that this is a user error on my end and we do not need to fix anything! 

For clarification, I had been comparing hardhat on IPC to my dev netowrk and saw these messages on my dev network. It makes sense to see eth_sendTransaction on a dev network, and we do not want them in Fendermint. Closing with comment
